language: java
jdk: openjdk13

matrix:
  include:
    - os: linux
      env:
        global:
          - FOLDER=lab1
          - FOLDER=lab2
          - FOLDER=lab3
          - FOLDER=lab4

script:
    - cd $FOLDER
    - mvn package
