language: java
jdk: openjdk13

os:
  - linux

env:
  matrix:
    - FOLDER=lab1
    - FOLDER=lab2
    - FOLDER=lab3
    - FOLDER=lab4
    - FOLDER=lab5
    - FOLDER=lab6

script:
  - chmod u+x travis_script.sh 
  - ./travis_script.sh